// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseForDirectory(arg1) {
  return window['go']['main']['App']['BrowseForDirectory'](arg1);
}

export function CleanDatabase() {
  return window['go']['main']['App']['CleanDatabase']();
}

export function GenerateReport() {
  return window['go']['main']['App']['GenerateReport']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SyncLibrary() {
  return window['go']['main']['App']['SyncLibrary']();
}
