// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function BrowseForDirectory(arg1:string):Promise<string>;

export function CleanDatabase():Promise<string>;

export function GenerateReport():Promise<string>;

export function GetConfig():Promise<config.Config>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SyncLibrary():Promise<string>;
